"""empty message

Revision ID: 9d21fea40252
Revises: 
Create Date: 2023-12-01 21:32:18.783237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d21fea40252'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predict', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sobrepeso', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('tabaquismo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predict', schema=None) as batch_op:
        batch_op.drop_column('tabaquismo')
        batch_op.drop_column('sobrepeso')

    # ### end Alembic commands ###
